### ISSUE TITLE
LDtk 1.0 checklist

### ISSUE THREAD

**Issue by Trouv** [Trouv/bevy_ecs_ldtk#68]
The `ldtk-1.0` branch is being developed to support the first major release of LDtk. This issue is intended to track new features that may need support, bugs that need fixing, design considerations, etc:

Required:
- [x] LDtk 1.0 files load
- [x] ldtk types updated
- [x] new field instances (entity refs, tiles) supported
- [ ] ~decent solution for using entity refs to create relational components~ spun off into its own issue #70
- [x] examples/sample files updated
- [x] Use iids instead of uids wherever applicable
- [x] multi-worlds doesn't break plugin

Bonus points:
- [x] Support for entity instances using field instance tiles for display
- [ ] more comprehensive multi-worlds support
- [ ] parallax layers support (not sure how this would even factor into the api, so maybe best to leave to the user)
- [ ] nine-slice entity display
- [ ] ~hot reloading for external levels (seems like it'll work now) #1~ It won't really work after all, though you can save twice as a workaround

**Comment by Trouv** [comment]
It's not all done yet but it's basically working on the `ldtk-1.0` branch now if you want to change your `Cargo.toml` to use it. I'm not gonna cut a new release with 1.0 support until bevy 0.7 and bevy_ecs_tilemap 0.6 come out since that's right around the corner, theoretically.
